const gemTypeItems = [
  { label: "Alexandrite", value: "alexandrite" },
  { label: "Almandine", value: "almandine" },
  { label: "Amazonite", value: "amazonite" },
  { label: "Amber", value: "amber" },
  { label: "Amethyst", value: "amethyst" },
  { label: "Ametrine", value: "ametrine" },
  { label: "Andalusite", value: "andalusite" },
  { label: "Andradite", value: "andradite" },
  { label: "Aquamarine", value: "aquamarine" },
  { label: "Aventurine Green", value: "aventurine_green" },
  { label: "Aventurine Yellow", value: "aventurine_yellow" },
  { label: "Benitoite", value: "benitoite" },
  { label: "Beryl Golden", value: "beryl_golden" },
  { label: "Bixbite", value: "bixbite" },
  { label: "Bloodstone", value: "bloodstone" },
  { label: "Blue Lace Agate", value: "blue_lace_agate" },
  { label: "Brazilianite", value: "brazilianite" },
  { label: "Carnelian", value: "carnelian" },
  { label: "Cats Eye", value: "cats_eye" },
  { label: "Chalcedony", value: "chalcedony" },
  { label: "Chalcedony Blue", value: "chalcedony_blue" },
  { label: "Chrome Diopside", value: "chrome_diopside" },
  { label: "Chrysoberyl", value: "chrysoberyl" },
  { label: "Chrysocolla", value: "chrysocolla" },
  { label: "Chrysoprase", value: "chrysoprase" },
  { label: "Citrine", value: "citrine" },
  { label: "Coral", value: "coral" },
  { label: "Danburite", value: "danburite" },
  { label: "Diamond", value: "diamond" },
  { label: "Diaspore", value: "diaspore" },
  { label: "Dumortierite", value: "dumortierite" },
  { label: "Emerald", value: "emerald" },
  { label: "Fluorite", value: "fluorite" },
  { label: "Garnet Red", value: "garnet_red" },
  { label: "Goshenite", value: "goshenite" },
  { label: "Grossular", value: "grossular" },
  { label: "Hessonite", value: "hessonite" },
  { label: "Hiddenite", value: "hiddenite" },
  { label: "Iolite", value: "iolite" },
  { label: "Jade", value: "jade" },
  { label: "Jasper", value: "jasper" },
  { label: "Kunzite", value: "kunzite" },
  { label: "Kyanite", value: "kyanite" },
  { label: "Labradorite", value: "labradorite" },
  { label: "Lapis Lazuli", value: "lapis_lazuli" },
  { label: "Larimar", value: "larimar" },
  { label: "Malachite", value: "malachite" },
  { label: "Moonstone", value: "moonstone" },
  { label: "Morganite", value: "morganite" },
  { label: "Onyx Black", value: "onyx_black" },
  { label: "Onyx Green", value: "onyx_green" },
  { label: "Onyx Red", value: "onyx_red" },
  { label: "Opal", value: "opal" },
  { label: "Pearl", value: "pearl" },
  { label: "Peridot", value: "peridot" },
  { label: "Prehnite", value: "prehnite" },
  { label: "Pyrite", value: "pyrite" },
  { label: "Pyrope", value: "pyrope" },
  { label: "Quartz Beer", value: "quartz_beer" },
  { label: "Quartz Lemon", value: "quartz_lemon" },
  { label: "Quartz Rose", value: "quartz_rose" },
  { label: "Quartz Rutilated", value: "quartz_rutilated" },
  { label: "Quartz Smoky", value: "quartz_smoky" },
  { label: "Rhodochrosite", value: "rhodochrosite" },
  { label: "Rhodolite", value: "rhodolite" },
  { label: "Rhodonite", value: "rhodonite" },
  { label: "Ruby", value: "ruby" },
  { label: "Sapphire Blue", value: "sapphire_blue" },
  { label: "Sapphire Pink", value: "sapphire_pink" },
  { label: "Sapphire Purple", value: "sapphire_purple" },
  { label: "Sapphire Yellow", value: "sapphire_yellow" },
  { label: "Scapolite", value: "scapolite" },
  { label: "Serpentine", value: "serpentine" },
  { label: "Sodalite", value: "sodalite" },
  { label: "Spessartite", value: "spessartite" },
  { label: "Sphene", value: "sphene" },
  { label: "Spinel", value: "spinel" },
  { label: "Spodumene", value: "spodumene" },
  { label: "Sunstone", value: "sunstone" },
  { label: "Tanzanite", value: "tanzanite" },
  { label: "Tigers Eye", value: "tigers_eye" },
  { label: "Topaz", value: "topaz" },
  { label: "Tourmaline", value: "tourmaline" },
  { label: "Tsavorite", value: "tsavorite" },
  { label: "Turquoise", value: "turquoise" },
  { label: "Variscite", value: "variscite" },
  { label: "Zircon", value: "zircon" },
  { label: "Zoisite", value: "zoisite" },
];

export { gemTypeItems }; // Export the gem types for use in other files
